### ISSUE TITLE
Display only company related to the projects of the current user

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#97]
Page of interest:  http://88.249.18.205:8090/ecoman/newcompany

When displaying the company page, we need to see only companies related to the projects of the current opened account (for confidentiality reasons). There is no need to see all existing companies on the platform (only super admin user should be able to see them).

**Comment by corner82** [comment]
Mr.Tuna has been coded related code blocks, so I assign him this issue, he later can mark milestone...

**Comment by tcgumus** [comment]
Seeing all companies can be beneficial for consultants to look and decide which companies they can work with. But we have implemented a new feature that users can now only see projects they can edit and they can see which companies they can edit also. So i think it solves this issue but you can decide to close this issue or comment on it. Im waiting for your respond :)

**Comment by gmassard** [comment]
No the issue is not solve. The "company" page (http://88.249.18.205:8090/ecoman/company) still show all companies. This means every consultant can access companies details and flow data of every companies. Confidentiality is not maintain.
Please adapt the "company" page in relation with the project page. One consultant can consult a list including only the companies included in his projects.

**Comment by tcgumus** [comment]
Now users only see the company details when they have a permission to edit it. So the detailed information about companies doesn't show up now. Only company name and general information can be seen by general users.

**Comment by gmassard** [comment]
hi Tuna,
The issue is not solve from my side. When working in a project, for exemple:
You are working on a project named: test Geneva 25.02.15

This project only has 2 companies inside it: Geneva1 and Geneva 2.

But when I'm going to "Company" page, I can still assess all information from many companies that are not in the project such as Alimar, Alkatem or Givaudan.

Nothing has change since my late visit! Did you test your work????

**Comment by tcgumus** [comment]
I have made changes to the confidentiality as i mentioned in the comment. You can see alimar,alkatem or givaudan since you are consultant of them. I can add a new button as "show only project companies" so when you click it you will only see the companies related to a project. Or i can only show the project companies when you are opened a project. When you didnt open a project company list will be same.

**Comment by tcgumus** [comment]
You want to see the companies in a project since you want to acces their dataset management page easily right?

**Comment by gmassard** [comment]
Ok, now I undestand. But I did not even know I was a consultant for those companies.
I guess to add a choice list to display only companies in the project, or all companies the consultant is recognize for... Ok?
Yes, and also to make sure that confidentiality between project are respected.

**Comment by tcgumus** [comment]
Ok i will look and made changes asap. I will let you know when it is finished.

**Comment by emilyvuylsteke** [comment]
I can still see the details of all companies on the "all companies" page. Where do we stand in the confidentiality discussion?

**Comment by tcgumus** [comment]
When you click on a company page that you are not a consultant of, you won't be able to see the detailed information about the company like dataset values. Also i have added "my companies" referring to the companies that you have opened and "project companies" referring to the companies that works in the opened project. So it looks like we have solved this issue with portal implementations. Please review and respond. Thanks

**Comment by tcgumus** [comment]
My companies, Project Companies pages have been added and tested.
